"""schema core/private/chatbot cho PostgreSQL

Tạo 3 schema, toàn bộ bảng nghiệp vụ, rồi chạy db/sql/views.sql (27 view + function
chatbot.ma_sv() + phân quyền chatbot_reader) và tạo login role cho Text2SQL.

Revision ID: c996469711a7
Revises: 
Create Date: 2026-09-25 22:36:07.681015
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from chatbot_haui.core.config import settings
from chatbot_haui.db.sql import read_sql


revision: str = 'c996469711a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _run_formatted(bind, template: str, **params) -> None:
    """Chạy DDL có tên role / mật khẩu: để Postgres tự quote bằng format(%I, %L).

    DDL không nhận bind parameter, còn tự nối chuỗi trong Python thì dễ sai quote.
    """
    stmt = bind.execute(sa.text(f"SELECT format({template})"), params).scalar()
    bind.execute(sa.text(stmt))


def _create_chatbot_login_role() -> None:
    """Login role cho Text2SQL: thành viên chatbot_reader, chỉ SELECT trên schema chatbot."""
    bind = op.get_bind()
    user, password = settings.db_chatbot_user, settings.db_chatbot_password
    exists = bind.execute(sa.text("SELECT 1 FROM pg_roles WHERE rolname = :u"), {"u": user}).scalar()
    verb = "ALTER" if exists else "CREATE"
    _run_formatted(bind, f"'{verb} ROLE %I LOGIN PASSWORD %L', CAST(:u AS text), CAST(:p AS text)", u=user, p=password)
    _run_formatted(bind, "'GRANT chatbot_reader TO %I', CAST(:u AS text)", u=user)
    # ALTER ROLE ... SET không di truyền qua quyền thành viên, phải đặt trên chính login role
    _run_formatted(bind, "'ALTER ROLE %I SET statement_timeout = %L', CAST(:u AS text), CAST(:t AS text)", u=user, t="5s")


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS private")
    op.execute("CREATE SCHEMA IF NOT EXISTS chatbot")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chinh_sach',
    sa.Column('ma_cs', sa.String(length=20), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.Column('nhom', sa.String(length=15), nullable=False),
    sa.Column('ty_le', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('co_so', sa.String(length=15), nullable=False),
    sa.Column('so_thang', sa.SmallInteger(), nullable=True),
    sa.Column('can_cu', sa.String(length=150), nullable=False),
    sa.CheckConstraint("co_so IN ('muc_tran', 'luong_co_so', 'hoc_phi', 'khac')", name='ck_chinh_sach_co_so'),
    sa.CheckConstraint("nhom IN ('mien_hp', 'giam_hp', 'ho_tro_cp', 'noi_tru', 'ho_tro_ht', 'ho_tro_haui')", name='ck_chinh_sach_nhom'),
    sa.PrimaryKeyConstraint('ma_cs'),
    schema='core'
    )
    op.create_table('doanh_nghiep',
    sa.Column('ma_dn', sa.String(length=10), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('dia_chi', sa.String(length=255), nullable=True),
    sa.Column('linh_vuc', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sdt', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('ma_dn'),
    schema='core'
    )
    op.create_table('doi_tuong',
    sa.Column('ma_dt', sa.String(length=30), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('ma_dt'),
    schema='core'
    )
    op.create_table('don_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=False),
    sa.Column('bac', sa.String(length=10), nullable=False),
    sa.Column('khoa_tu', sa.Integer(), nullable=False),
    sa.Column('khoa_den', sa.Integer(), nullable=False),
    sa.Column('hinh_thuc', sa.String(length=10), nullable=False),
    sa.Column('loai_ctdt', sa.String(length=10), nullable=False),
    sa.Column('nhom_mon', sa.String(length=10), server_default='tat_ca', nullable=False),
    sa.Column('don_gia', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('don_vi', sa.String(length=10), nullable=False),
    sa.Column('so_qd', sa.String(length=30), nullable=False),
    sa.CheckConstraint("bac IN ('dai_hoc', 'ky_su', 'cao_dang')", name='ck_don_gia_bac'),
    sa.CheckConstraint("don_vi IN ('tc', 'thang', 'nam')", name='ck_don_gia_don_vi'),
    sa.CheckConstraint("hinh_thuc IN ('chinh_quy', 'vlvh', 'tu_xa')", name='ck_don_gia_hinh_thuc'),
    sa.CheckConstraint("loai_ctdt IN ('dai_tra', 'tieng_anh', 'tat_ca')", name='ck_don_gia_loai_ctdt'),
    sa.CheckConstraint("nhom_mon IN ('tat_ca', 'gdtc_gdqp')", name='ck_don_gia_nhom_mon'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('he_so_tc',
    sa.Column('loai_tc', sa.String(length=10), nullable=False),
    sa.Column('he_so', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('mo_ta', sa.String(length=200), nullable=False),
    sa.CheckConstraint("loai_tc IN ('lt', 'dac_thu', 'th')", name='ck_he_so_tc_loai'),
    sa.PrimaryKeyConstraint('loai_tc'),
    schema='core'
    )
    op.create_table('hoc_ky',
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=False),
    sa.Column('loai', sa.String(length=5), nullable=False),
    sa.Column('ten', sa.String(length=50), nullable=False),
    sa.Column('ma_hk_chinh', sa.CHAR(length=5), nullable=False),
    sa.Column('ngay_bd', sa.Date(), nullable=True),
    sa.Column('ngay_kt', sa.Date(), nullable=True),
    sa.CheckConstraint("loai = 'phu' OR ma_hk_chinh = ma_hk", name='ck_hoc_ky_chinh_tu_tro'),
    sa.CheckConstraint("loai IN ('chinh', 'phu')", name='ck_hoc_ky_loai'),
    sa.ForeignKeyConstraint(['ma_hk_chinh'], ['core.hoc_ky.ma_hk'], ),
    sa.PrimaryKeyConstraint('ma_hk'),
    schema='core'
    )
    op.create_table('khoa',
    sa.Column('ma_khoa', sa.String(length=10), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ma_khoa'),
    schema='core'
    )
    op.create_table('khoan_thu',
    sa.Column('ma_kt', sa.String(length=20), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=True),
    sa.Column('bac', sa.String(length=10), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('chu_ky', sa.String(length=30), nullable=False),
    sa.Column('tu_ngay', sa.Date(), nullable=True),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.String(length=300), nullable=True),
    sa.Column('so_qd', sa.String(length=30), nullable=True),
    sa.CheckConstraint("bac IN ('dai_hoc', 'ky_su', 'cao_dang', 'lien_thong', 'tat_ca')", name='ck_khoan_thu_bac'),
    sa.PrimaryKeyConstraint('ma_kt'),
    schema='core'
    )
    op.create_table('khoi_nganh',
    sa.Column('ma_khoi', sa.String(length=20), nullable=False),
    sa.Column('bac', sa.String(length=10), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.CheckConstraint("bac IN ('dai_hoc', 'cao_dang')", name='ck_khoi_nganh_bac'),
    sa.PrimaryKeyConstraint('ma_khoi'),
    schema='core'
    )
    op.create_table('loai_hb',
    sa.Column('ma_loai', sa.String(length=15), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('nhom', sa.String(length=10), nullable=False),
    sa.Column('chu_ky', sa.String(length=10), nullable=False),
    sa.Column('van_ban', sa.String(length=150), nullable=False),
    sa.CheckConstraint("chu_ky IN ('hoc_ky', 'nam_hoc')", name='ck_loai_hb_chu_ky'),
    sa.CheckConstraint("nhom IN ('haui', 'kkht', 'thac_si', 'tai_tro', 'ntb')", name='ck_loai_hb_nhom'),
    sa.PrimaryKeyConstraint('ma_loai'),
    schema='core'
    )
    op.create_table('mon',
    sa.Column('ma_mon', sa.String(length=10), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('so_tc', sa.SmallInteger(), nullable=False),
    sa.Column('tc_lt', sa.Numeric(precision=3, scale=1), server_default='0', nullable=False),
    sa.Column('tc_dac_thu', sa.Numeric(precision=3, scale=1), server_default='0', nullable=False),
    sa.Column('tc_th', sa.Numeric(precision=3, scale=1), server_default='0', nullable=False),
    sa.Column('loai', sa.String(length=15), server_default='thuong', nullable=False),
    sa.Column('tinh_tb', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('xet_hb', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("loai IN ('thuong', 'gdtc', 'gdqp', 'cntt', 'ngoai_ngu', 'thuc_tap', 'do_an')", name='ck_mon_loai'),
    sa.CheckConstraint('so_tc > 0', name='ck_mon_so_tc'),
    sa.CheckConstraint('tc_lt + tc_dac_thu + tc_th = so_tc', name='ck_mon_tong_tc'),
    sa.PrimaryKeyConstraint('ma_mon'),
    schema='core'
    )
    op.create_table('nien_khoa',
    sa.Column('ma_nk', sa.String(length=10), nullable=False),
    sa.Column('bac', sa.String(length=10), nullable=False),
    sa.Column('so_khoa', sa.SmallInteger(), nullable=False),
    sa.Column('nam_nhap_hoc', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("bac IN ('dai_hoc', 'ky_su', 'cao_dang')", name='ck_nien_khoa_bac'),
    sa.PrimaryKeyConstraint('ma_nk'),
    schema='core'
    )
    op.create_table('tham_so',
    sa.Column('ma', sa.String(length=30), nullable=False),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('gia_tri', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ma', 'tu_ngay'),
    schema='core'
    )
    op.create_table('thang_diem',
    sa.Column('diem_chu', sa.String(length=2), nullable=False),
    sa.Column('tu', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('den', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('diem_4', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('dat', sa.Boolean(), nullable=True),
    sa.Column('tinh_tb', sa.Boolean(), nullable=False),
    sa.Column('mo_ta', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('diem_chu'),
    schema='core'
    )
    op.create_table('giang_vien',
    sa.Column('ma_gv', sa.String(length=10), nullable=False),
    sa.Column('ho_ten', sa.String(length=60), nullable=False),
    sa.Column('ma_khoa', sa.String(length=10), nullable=False),
    sa.Column('hoc_vi', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sdt', sa.String(length=15), nullable=True),
    sa.CheckConstraint("hoc_vi IN ('ths', 'ts', 'pgs', 'gs')", name='ck_giang_vien_hoc_vi'),
    sa.ForeignKeyConstraint(['ma_khoa'], ['core.khoa.ma_khoa'], ),
    sa.PrimaryKeyConstraint('ma_gv'),
    schema='core'
    )
    op.create_table('muc_hb',
    sa.Column('ma_loai', sa.String(length=15), nullable=False),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=False),
    sa.Column('xep_loai', sa.String(length=10), server_default='chung', nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('ty_le', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ghi_chu', sa.String(length=200), nullable=True),
    sa.CheckConstraint("xep_loai IN ('xuat_sac', 'gioi', 'kha', 'chung')", name='ck_muc_hb_xep_loai'),
    sa.CheckConstraint('so_tien IS NOT NULL OR ty_le IS NOT NULL', name='ck_muc_hb_gia_tri'),
    sa.ForeignKeyConstraint(['ma_loai'], ['core.loai_hb.ma_loai'], ),
    sa.PrimaryKeyConstraint('ma_loai', 'nam_hoc', 'xep_loai'),
    schema='core'
    )
    op.create_table('muc_tran',
    sa.Column('ma_khoi', sa.String(length=20), nullable=False),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=False),
    sa.Column('muc_thang', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['ma_khoi'], ['core.khoi_nganh.ma_khoi'], ),
    sa.PrimaryKeyConstraint('ma_khoi', 'nam_hoc'),
    schema='core'
    )
    op.create_table('nganh',
    sa.Column('ma_nganh', sa.String(length=10), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('ma_khoa', sa.String(length=10), nullable=False),
    sa.Column('ma_khoi', sa.String(length=20), nullable=False),
    sa.Column('khoi_ntb', sa.String(length=10), nullable=False),
    sa.CheckConstraint("khoi_ntb IN ('ky_thuat', 'xa_hoi')", name='ck_nganh_khoi_ntb'),
    sa.ForeignKeyConstraint(['ma_khoa'], ['core.khoa.ma_khoa'], ),
    sa.ForeignKeyConstraint(['ma_khoi'], ['core.khoi_nganh.ma_khoi'], ),
    sa.PrimaryKeyConstraint('ma_nganh'),
    schema='core'
    )
    op.create_table('ctdt',
    sa.Column('ma_ctdt', sa.String(length=15), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('ma_nganh', sa.String(length=10), nullable=False),
    sa.Column('ma_nk', sa.String(length=10), nullable=False),
    sa.Column('hinh_thuc', sa.String(length=10), nullable=False),
    sa.Column('loai', sa.String(length=10), nullable=False),
    sa.Column('so_tc', sa.SmallInteger(), nullable=False),
    sa.Column('so_hk', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("hinh_thuc IN ('chinh_quy', 'vlvh', 'tu_xa')", name='ck_ctdt_hinh_thuc'),
    sa.CheckConstraint("loai IN ('dai_tra', 'tieng_anh')", name='ck_ctdt_loai'),
    sa.ForeignKeyConstraint(['ma_nganh'], ['core.nganh.ma_nganh'], ),
    sa.ForeignKeyConstraint(['ma_nk'], ['core.nien_khoa.ma_nk'], ),
    sa.PrimaryKeyConstraint('ma_ctdt'),
    schema='core'
    )
    op.create_table('lop_hp',
    sa.Column('ma_lop', sa.String(length=20), nullable=False),
    sa.Column('ma_mon', sa.String(length=10), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('theo_yeu_cau', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('si_so', sa.SmallInteger(), nullable=True),
    sa.Column('he_so', sa.Numeric(precision=2, scale=1), server_default='1.0', nullable=False),
    sa.Column('ma_gv', sa.String(length=10), nullable=True),
    sa.Column('phong', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ma_gv'], ['core.giang_vien.ma_gv'], ),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_mon'], ['core.mon.ma_mon'], ),
    sa.PrimaryKeyConstraint('ma_lop'),
    schema='core'
    )
    op.create_index('ix_lop_hp_hk', 'lop_hp', ['ma_hk'], unique=False, schema='core')
    op.create_table('lich_hoc',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_lop', sa.String(length=20), nullable=False),
    sa.Column('thu', sa.SmallInteger(), nullable=False),
    sa.Column('tiet_bd', sa.SmallInteger(), nullable=False),
    sa.Column('so_tiet', sa.SmallInteger(), nullable=False),
    sa.Column('phong', sa.String(length=20), nullable=True),
    sa.Column('tuan_bd', sa.SmallInteger(), nullable=True),
    sa.Column('tuan_kt', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('so_tiet BETWEEN 1 AND 6', name='ck_lich_hoc_so_tiet'),
    sa.CheckConstraint('thu BETWEEN 2 AND 8', name='ck_lich_hoc_thu'),
    sa.CheckConstraint('tiet_bd BETWEEN 1 AND 15', name='ck_lich_hoc_tiet_bd'),
    sa.CheckConstraint('tuan_kt IS NULL OR tuan_bd IS NULL OR tuan_kt >= tuan_bd', name='ck_lich_hoc_tuan'),
    sa.ForeignKeyConstraint(['ma_lop'], ['core.lop_hp.ma_lop'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_lop', 'thu', 'tiet_bd', name='uq_lich_hoc_ca'),
    schema='core'
    )
    op.create_index('ix_lich_hoc_lop', 'lich_hoc', ['ma_lop'], unique=False, schema='core')
    op.create_table('lich_thi',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_lop', sa.String(length=20), nullable=False),
    sa.Column('lan_thi', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('thoi_gian', sa.DateTime(), nullable=False),
    sa.Column('so_phut', sa.SmallInteger(), nullable=False),
    sa.Column('hinh_thuc', sa.String(length=15), nullable=False),
    sa.Column('phong', sa.String(length=20), nullable=True),
    sa.CheckConstraint("hinh_thuc IN ('tu_luan', 'trac_nghiem', 'van_dap', 'thuc_hanh', 'tieu_luan')", name='ck_lich_thi_hinh_thuc'),
    sa.CheckConstraint('lan_thi IN (1, 2)', name='ck_lich_thi_lan'),
    sa.CheckConstraint('so_phut BETWEEN 15 AND 300', name='ck_lich_thi_so_phut'),
    sa.ForeignKeyConstraint(['ma_lop'], ['core.lop_hp.ma_lop'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_lop', 'lan_thi', name='uq_lich_thi_lop_lan'),
    schema='core'
    )
    op.create_index('ix_lich_thi_lop', 'lich_thi', ['ma_lop'], unique=False, schema='core')
    op.create_table('nhom_tu_chon',
    sa.Column('ma_nhom', sa.String(length=15), nullable=False),
    sa.Column('ma_ctdt', sa.String(length=15), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('so_tc', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ma_ctdt'], ['core.ctdt.ma_ctdt'], ),
    sa.PrimaryKeyConstraint('ma_nhom'),
    schema='core'
    )
    op.create_table('sinh_vien',
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ho_ten', sa.String(length=60), nullable=False),
    sa.Column('ma_ctdt', sa.String(length=15), nullable=False),
    sa.Column('ma_ctdt_2', sa.String(length=15), nullable=True),
    sa.Column('lop', sa.String(length=20), nullable=True),
    sa.Column('ngay_nhap_hoc', sa.Date(), nullable=False),
    sa.Column('trang_thai', sa.String(length=15), server_default='dang_hoc', nullable=False),
    sa.Column('hb_dau_vao', sa.String(length=15), nullable=True),
    sa.Column('ngay_sinh', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sdt', sa.String(length=15), nullable=True),
    sa.Column('dia_chi', sa.String(length=255), nullable=True),
    sa.Column('dan_toc', sa.String(length=30), nullable=True),
    sa.Column('quoc_tich', sa.String(length=50), nullable=True),
    sa.CheckConstraint("hb_dau_vao IN ('toan_khoa', 'nam_nhat', '5_trieu')", name='ck_sinh_vien_hb_dau_vao'),
    sa.CheckConstraint("trang_thai IN ('dang_hoc', 'bao_luu', 'dinh_chi', 'thoi_hoc', 'tot_nghiep')", name='ck_sinh_vien_trang_thai'),
    sa.ForeignKeyConstraint(['ma_ctdt'], ['core.ctdt.ma_ctdt'], ),
    sa.ForeignKeyConstraint(['ma_ctdt_2'], ['core.ctdt.ma_ctdt'], ),
    sa.PrimaryKeyConstraint('ma_sv'),
    schema='core'
    )
    op.create_table('bien_dong',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('loai', sa.String(length=15), nullable=False),
    sa.Column('so_qd', sa.String(length=30), nullable=True),
    sa.Column('ngay_qd', sa.Date(), nullable=False),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.CheckConstraint("loai IN ('bao_luu', 'tro_lai', 'thoi_hoc', 'buoc_thoi_hoc', 'chuyen_nganh', 'tot_nghiep')", name='ck_bien_dong_loai'),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('ctdt_mon',
    sa.Column('ma_ctdt', sa.String(length=15), nullable=False),
    sa.Column('ma_mon', sa.String(length=10), nullable=False),
    sa.Column('bat_buoc', sa.Boolean(), nullable=False),
    sa.Column('ma_nhom', sa.String(length=15), nullable=True),
    sa.Column('hk_thu', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('bat_buoc OR ma_nhom IS NOT NULL', name='ck_ctdt_mon_nhom'),
    sa.ForeignKeyConstraint(['ma_ctdt'], ['core.ctdt.ma_ctdt'], ),
    sa.ForeignKeyConstraint(['ma_mon'], ['core.mon.ma_mon'], ),
    sa.ForeignKeyConstraint(['ma_nhom'], ['core.nhom_tu_chon.ma_nhom'], ),
    sa.PrimaryKeyConstraint('ma_ctdt', 'ma_mon'),
    schema='core'
    )
    op.create_table('dang_ky',
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_lop', sa.String(length=20), nullable=False),
    sa.Column('ngay', sa.Date(), nullable=False),
    sa.Column('loai', sa.String(length=10), nullable=False),
    sa.Column('trang_thai', sa.String(length=10), server_default='dang_ky', nullable=False),
    sa.CheckConstraint("loai IN ('lan_dau', 'hoc_lai', 'cai_thien', 'hoc_doi')", name='ck_dang_ky_loai'),
    sa.CheckConstraint("trang_thai IN ('dang_ky', 'da_huy')", name='ck_dang_ky_trang_thai'),
    sa.ForeignKeyConstraint(['ma_lop'], ['core.lop_hp.ma_lop'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_sv', 'ma_lop'),
    schema='core'
    )
    op.create_index('ix_dang_ky_lop', 'dang_ky', ['ma_lop'], unique=False, schema='core')
    op.create_table('diem_hp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_mon', sa.String(length=10), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('ma_lop', sa.String(length=20), nullable=True),
    sa.Column('lan_hoc', sa.SmallInteger(), nullable=False),
    sa.Column('diem_qt', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('diem_thi', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('diem_10', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('diem_chu', sa.String(length=2), nullable=True),
    sa.Column('chinh_thuc', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('diem_10 BETWEEN 0 AND 10', name='ck_diem_hp_10'),
    sa.CheckConstraint('diem_qt BETWEEN 0 AND 10', name='ck_diem_hp_qt'),
    sa.CheckConstraint('diem_thi BETWEEN 0 AND 10', name='ck_diem_hp_thi'),
    sa.CheckConstraint('lan_hoc >= 1', name='ck_diem_hp_lan_hoc'),
    sa.ForeignKeyConstraint(['diem_chu'], ['core.thang_diem.diem_chu'], ),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_lop'], ['core.lop_hp.ma_lop'], ),
    sa.ForeignKeyConstraint(['ma_mon'], ['core.mon.ma_mon'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_sv', 'ma_mon', 'lan_hoc', name='uq_diem_hp_lan'),
    schema='core'
    )
    op.create_index('ix_diem_hp_sv_hk', 'diem_hp', ['ma_sv', 'ma_hk'], unique=False, schema='core')
    op.create_index('uq_diem_chinh_thuc', 'diem_hp', ['ma_sv', 'ma_mon'], unique=True, schema='core', postgresql_where='chinh_thuc')
    op.create_table('dk_tot_nghiep',
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('loai', sa.String(length=10), nullable=False),
    sa.Column('dat', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ngay_dat', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.String(length=200), nullable=True),
    sa.CheckConstraint("loai IN ('ngoai_ngu', 'cntt', 'gdtc', 'gdqp')", name='ck_dk_tot_nghiep_loai'),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_sv', 'loai'),
    schema='core'
    )
    op.create_table('hoc_bong',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_loai', sa.String(length=15), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=True),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=True),
    sa.Column('xep_loai', sa.String(length=10), nullable=True),
    sa.Column('dt_ntb', sa.String(length=10), nullable=True),
    sa.Column('nha_tai_tro', sa.String(length=150), nullable=True),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('so_qd', sa.String(length=30), nullable=True),
    sa.Column('ngay_qd', sa.Date(), nullable=True),
    sa.CheckConstraint("xep_loai IN ('xuat_sac', 'gioi', 'kha')", name='ck_hoc_bong_xep_loai'),
    sa.CheckConstraint('ma_hk IS NOT NULL OR nam_hoc IS NOT NULL', name='ck_hoc_bong_dot'),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_loai'], ['core.loai_hb.ma_loai'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_hoc_bong_sv', 'hoc_bong', ['ma_sv'], unique=False, schema='core')
    op.create_table('ket_qua_hk',
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('tc_dk', sa.SmallInteger(), nullable=False),
    sa.Column('tc_dat', sa.SmallInteger(), nullable=False),
    sa.Column('tc_truot', sa.SmallInteger(), nullable=False),
    sa.Column('tb_hk', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('tc_tich_luy', sa.SmallInteger(), nullable=False),
    sa.Column('tb_tich_luy', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('xep_loai', sa.String(length=12), nullable=True),
    sa.Column('nam_thu', sa.SmallInteger(), nullable=True),
    sa.Column('canh_bao', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("xep_loai IN ('xuat_sac', 'gioi', 'kha', 'trung_binh', 'yeu', 'kem')", name='ck_ket_qua_hk_xep_loai'),
    sa.CheckConstraint('nam_thu BETWEEN 1 AND 4', name='ck_ket_qua_hk_nam_thu'),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_sv', 'ma_hk'),
    schema='core'
    )
    op.create_table('ky_luat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('hinh_thuc', sa.String(length=15), nullable=False),
    sa.Column('so_qd', sa.String(length=30), nullable=False),
    sa.Column('ngay_qd', sa.Date(), nullable=False),
    sa.Column('het_hieu_luc', sa.Date(), nullable=True),
    sa.Column('noi_dung', sa.Text(), nullable=True),
    sa.CheckConstraint("hinh_thuc IN ('khien_trach', 'canh_cao', 'dinh_chi', 'buoc_thoi_hoc')", name='ck_ky_luat_hinh_thuc'),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_ky_luat_sv', 'ky_luat', ['ma_sv'], unique=False, schema='core')
    op.create_table('lich_thi_sv',
    sa.Column('ma_lich_thi', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('so_bd', sa.SmallInteger(), nullable=False),
    sa.Column('vi_tri', sa.String(length=10), nullable=True),
    sa.Column('du_dieu_kien', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ly_do', sa.String(length=200), nullable=True),
    sa.CheckConstraint('du_dieu_kien OR ly_do IS NOT NULL', name='ck_lich_thi_sv_ly_do'),
    sa.CheckConstraint('so_bd > 0', name='ck_lich_thi_sv_so_bd'),
    sa.ForeignKeyConstraint(['ma_lich_thi'], ['core.lich_thi.id'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_lich_thi', 'ma_sv'),
    schema='core'
    )
    op.create_index('ix_lich_thi_sv_sv', 'lich_thi_sv', ['ma_sv'], unique=False, schema='core')
    op.create_table('phai_thu',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('loai', sa.String(length=10), nullable=False),
    sa.Column('ma_lop', sa.String(length=20), nullable=True),
    sa.Column('ma_kt', sa.String(length=20), nullable=True),
    sa.Column('n_hp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('he_so_lop', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('don_gia', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('han_nop', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.String(length=10), server_default='hieu_luc', nullable=False),
    sa.CheckConstraint("loai <> 'hoc_phi' OR ma_lop IS NOT NULL", name='ck_phai_thu_hoc_phi_co_lop'),
    sa.CheckConstraint("loai IN ('hoc_phi', 'khoan_thu', 'phi_phat', 'khac')", name='ck_phai_thu_loai'),
    sa.CheckConstraint("trang_thai IN ('hieu_luc', 'da_huy')", name='ck_phai_thu_trang_thai'),
    sa.CheckConstraint('so_tien >= 0', name='ck_phai_thu_so_tien'),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_kt'], ['core.khoan_thu.ma_kt'], ),
    sa.ForeignKeyConstraint(['ma_lop'], ['core.lop_hp.ma_lop'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_phai_thu_sv_hk', 'phai_thu', ['ma_sv', 'ma_hk'], unique=False, schema='core')
    op.create_table('ren_luyen',
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('diem', sa.SmallInteger(), nullable=False),
    sa.Column('xep_loai', sa.String(length=12), nullable=False),
    sa.CheckConstraint("xep_loai IN ('xuat_sac', 'tot', 'kha', 'trung_binh', 'yeu', 'kem')", name='ck_ren_luyen_xep_loai'),
    sa.CheckConstraint('diem BETWEEN 0 AND 100', name='ck_ren_luyen_diem'),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_sv', 'ma_hk'),
    schema='core'
    )
    op.create_table('sv_chinh_sach',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_cs', sa.String(length=20), nullable=False),
    sa.Column('ma_dt', sa.String(length=30), nullable=True),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.Column('so_qd', sa.String(length=30), nullable=True),
    sa.Column('trang_thai', sa.String(length=10), server_default='dang_huong', nullable=False),
    sa.CheckConstraint("trang_thai IN ('dang_huong', 'tam_dung', 'ket_thuc')", name='ck_sv_chinh_sach_trang_thai'),
    sa.ForeignKeyConstraint(['ma_cs'], ['core.chinh_sach.ma_cs'], ),
    sa.ForeignKeyConstraint(['ma_dt'], ['core.doi_tuong.ma_dt'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_sv_cs_sv', 'sv_chinh_sach', ['ma_sv'], unique=False, schema='core')
    op.create_table('sv_doi_tuong',
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_dt', sa.String(length=30), nullable=False),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.String(length=10), server_default='cho_duyet', nullable=False),
    sa.CheckConstraint("trang_thai IN ('cho_duyet', 'da_duyet', 'tu_choi')", name='ck_sv_doi_tuong_trang_thai'),
    sa.ForeignKeyConstraint(['ma_dt'], ['core.doi_tuong.ma_dt'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_sv', 'ma_dt', 'tu_ngay'),
    schema='core'
    )
    op.create_table('thanh_tich',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('nam_hoc', sa.CHAR(length=9), nullable=False),
    sa.Column('loai', sa.String(length=15), nullable=False),
    sa.Column('cap', sa.String(length=10), nullable=False),
    sa.Column('giai', sa.String(length=20), nullable=False),
    sa.Column('cuoc_thi', sa.String(length=200), nullable=True),
    sa.CheckConstraint("cap IN ('truong', 'tinh', 'quoc_gia', 'khu_vuc', 'quoc_te')", name='ck_thanh_tich_cap'),
    sa.CheckConstraint("loai IN ('nckh', 'tay_nghe', 'olympic', 'khac')", name='ck_thanh_tich_loai'),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('thuc_tap',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('ma_dn', sa.String(length=10), nullable=False),
    sa.Column('ma_hk', sa.CHAR(length=5), nullable=False),
    sa.Column('ma_mon', sa.String(length=10), nullable=True),
    sa.Column('ma_gv', sa.String(length=10), nullable=True),
    sa.Column('vi_tri', sa.String(length=100), nullable=True),
    sa.Column('tu_ngay', sa.Date(), nullable=False),
    sa.Column('den_ngay', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.String(length=15), server_default='dang_thuc_tap', nullable=False),
    sa.Column('diem', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.CheckConstraint("trang_thai IN ('dang_thuc_tap', 'hoan_thanh', 'huy')", name='ck_thuc_tap_trang_thai'),
    sa.CheckConstraint('den_ngay IS NULL OR den_ngay >= tu_ngay', name='ck_thuc_tap_ngay'),
    sa.CheckConstraint('diem BETWEEN 0 AND 10', name='ck_thuc_tap_diem'),
    sa.ForeignKeyConstraint(['ma_dn'], ['core.doanh_nghiep.ma_dn'], ),
    sa.ForeignKeyConstraint(['ma_gv'], ['core.giang_vien.ma_gv'], ),
    sa.ForeignKeyConstraint(['ma_hk'], ['core.hoc_ky.ma_hk'], ),
    sa.ForeignKeyConstraint(['ma_mon'], ['core.mon.ma_mon'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_thuc_tap_sv', 'thuc_tap', ['ma_sv'], unique=False, schema='core')
    op.create_table('tai_khoan',
    sa.Column('ten_dn', sa.String(length=50), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=True),
    sa.Column('mat_khau', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ten_dn'),
    sa.UniqueConstraint('ma_sv'),
    schema='private'
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['private.tai_khoan.ten_dn'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_username'), 'chat_message', ['username'], unique=False)
    op.create_table('giao_dich',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ma_sv', sa.String(length=12), nullable=False),
    sa.Column('thoi_gian', sa.DateTime(), nullable=False),
    sa.Column('loai', sa.String(length=15), nullable=False),
    sa.Column('chieu', sa.String(length=3), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('ma_phai_thu', sa.BigInteger(), nullable=True),
    sa.Column('ma_hb', sa.BigInteger(), nullable=True),
    sa.Column('trang_thai', sa.String(length=12), nullable=False),
    sa.Column('kenh', sa.String(length=20), nullable=True),
    sa.Column('ghi_chu', sa.String(length=300), nullable=True),
    sa.CheckConstraint("chieu IN ('vao', 'ra')", name='ck_giao_dich_chieu'),
    sa.CheckConstraint("loai IN ('nap_tien', 'rut_tien', 'thanh_toan', 'hoan_tien', 'nhan_hb', 'nhan_mghp', 'nhan_ho_tro')", name='ck_giao_dich_loai'),
    sa.CheckConstraint("trang_thai IN ('thanh_cong', 'that_bai', 'dang_xu_ly')", name='ck_giao_dich_trang_thai'),
    sa.CheckConstraint('so_tien > 0', name='ck_giao_dich_so_tien'),
    sa.ForeignKeyConstraint(['ma_hb'], ['core.hoc_bong.id'], ),
    sa.ForeignKeyConstraint(['ma_phai_thu'], ['core.phai_thu.id'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['core.sinh_vien.ma_sv'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_giao_dich_sv', 'giao_dich', ['ma_sv', 'thoi_gian'], unique=False, schema='core')
    # ### end Alembic commands ###

    # View + function + phân quyền: giữ nguyên văn trong db/sql/views.sql
    op.execute(read_sql("views.sql"))
    # views.sql đặt search_path = core; trả lại để lệnh sau (alembic_version ở public) không lệch schema
    op.execute("RESET search_path")
    _create_chatbot_login_role()


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS chatbot CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_giao_dich_sv', table_name='giao_dich', schema='core')
    op.drop_table('giao_dich', schema='core')
    op.drop_index(op.f('ix_chat_message_username'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('tai_khoan', schema='private')
    op.drop_index('ix_thuc_tap_sv', table_name='thuc_tap', schema='core')
    op.drop_table('thuc_tap', schema='core')
    op.drop_table('thanh_tich', schema='core')
    op.drop_table('sv_doi_tuong', schema='core')
    op.drop_index('ix_sv_cs_sv', table_name='sv_chinh_sach', schema='core')
    op.drop_table('sv_chinh_sach', schema='core')
    op.drop_table('ren_luyen', schema='core')
    op.drop_index('ix_phai_thu_sv_hk', table_name='phai_thu', schema='core')
    op.drop_table('phai_thu', schema='core')
    op.drop_index('ix_lich_thi_sv_sv', table_name='lich_thi_sv', schema='core')
    op.drop_table('lich_thi_sv', schema='core')
    op.drop_index('ix_ky_luat_sv', table_name='ky_luat', schema='core')
    op.drop_table('ky_luat', schema='core')
    op.drop_table('ket_qua_hk', schema='core')
    op.drop_index('ix_hoc_bong_sv', table_name='hoc_bong', schema='core')
    op.drop_table('hoc_bong', schema='core')
    op.drop_table('dk_tot_nghiep', schema='core')
    op.drop_index('uq_diem_chinh_thuc', table_name='diem_hp', schema='core', postgresql_where='chinh_thuc')
    op.drop_index('ix_diem_hp_sv_hk', table_name='diem_hp', schema='core')
    op.drop_table('diem_hp', schema='core')
    op.drop_index('ix_dang_ky_lop', table_name='dang_ky', schema='core')
    op.drop_table('dang_ky', schema='core')
    op.drop_table('ctdt_mon', schema='core')
    op.drop_table('bien_dong', schema='core')
    op.drop_table('sinh_vien', schema='core')
    op.drop_table('nhom_tu_chon', schema='core')
    op.drop_index('ix_lich_thi_lop', table_name='lich_thi', schema='core')
    op.drop_table('lich_thi', schema='core')
    op.drop_index('ix_lich_hoc_lop', table_name='lich_hoc', schema='core')
    op.drop_table('lich_hoc', schema='core')
    op.drop_index('ix_lop_hp_hk', table_name='lop_hp', schema='core')
    op.drop_table('lop_hp', schema='core')
    op.drop_table('ctdt', schema='core')
    op.drop_table('nganh', schema='core')
    op.drop_table('muc_tran', schema='core')
    op.drop_table('muc_hb', schema='core')
    op.drop_table('giang_vien', schema='core')
    op.drop_table('thang_diem', schema='core')
    op.drop_table('tham_so', schema='core')
    op.drop_table('nien_khoa', schema='core')
    op.drop_table('mon', schema='core')
    op.drop_table('loai_hb', schema='core')
    op.drop_table('khoi_nganh', schema='core')
    op.drop_table('khoan_thu', schema='core')
    op.drop_table('khoa', schema='core')
    op.drop_table('hoc_ky', schema='core')
    op.drop_table('he_so_tc', schema='core')
    op.drop_table('don_gia', schema='core')
    op.drop_table('doi_tuong', schema='core')
    op.drop_table('doanh_nghiep', schema='core')
    op.drop_table('chinh_sach', schema='core')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS private CASCADE")
    op.execute("DROP SCHEMA IF EXISTS core CASCADE")
