"""initial schema

Revision ID: a1ee8f6ee390
Revises: 
Create Date: 2026-09-17 15:54:24.045119
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a1ee8f6ee390'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doanhNghiep',
    sa.Column('maDN', sa.CHAR(length=10), nullable=False),
    sa.Column('tenDN', sa.VARCHAR(length=50), nullable=True),
    sa.Column('diaChi', sa.VARCHAR(length=50), nullable=True),
    sa.Column('soDT', sa.CHAR(length=10), nullable=True),
    sa.Column('email', sa.CHAR(length=50), nullable=True),
    sa.Column('chuyenNganh', sa.VARCHAR(length=50), nullable=True),
    sa.Column('soLuongSV', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('maDN')
    )
    op.create_table('ketQuaHocKy',
    sa.Column('maKQHY', sa.CHAR(length=10), nullable=False),
    sa.Column('hocKy', sa.Integer(), nullable=True),
    sa.Column('TongTC', sa.Integer(), nullable=True),
    sa.Column('diemTBC', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('maKQHY')
    )
    op.create_table('khoa',
    sa.Column('maKhoa', sa.CHAR(length=10), nullable=False),
    sa.Column('tenKhoa', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('maKhoa'),
    sa.UniqueConstraint('maKhoa')
    )
    op.create_table('khoangThuKhac',
    sa.Column('maKT', sa.CHAR(length=10), nullable=False),
    sa.Column('tenKT', sa.VARCHAR(length=50), nullable=True),
    sa.Column('gia', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('ngayBD', sa.Date(), nullable=True),
    sa.Column('han', sa.Date(), nullable=True),
    sa.Column('giaChu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('maKT')
    )
    op.create_table('lichThi',
    sa.Column('maLT', sa.CHAR(length=10), nullable=False),
    sa.Column('soPhong', sa.Integer(), nullable=True),
    sa.Column('gioBD', sa.DateTime(), nullable=True),
    sa.Column('gioKT', sa.DateTime(), nullable=True),
    sa.Column('hinhThucThi', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('maLT')
    )
    op.create_table('nhomMH',
    sa.Column('maNhom', sa.CHAR(length=20), nullable=False),
    sa.Column('TenNhom', sa.VARCHAR(length=50), nullable=True),
    sa.Column('loaiNhom', sa.VARCHAR(length=20), nullable=True),
    sa.Column('soTC_YC', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('maNhom')
    )
    op.create_table('ctdt',
    sa.Column('maCT', sa.CHAR(length=10), nullable=False),
    sa.Column('nganhHoc', sa.VARCHAR(length=50), nullable=True),
    sa.Column('khoaHoc', sa.VARCHAR(length=10), nullable=True),
    sa.Column('soTC_YeuCau', sa.Integer(), nullable=True),
    sa.Column('soMon', sa.Integer(), nullable=True),
    sa.Column('maKhoa', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maKhoa'], ['khoa.maKhoa'], ),
    sa.PrimaryKeyConstraint('maCT'),
    sa.UniqueConstraint('maCT')
    )
    op.create_table('giangVien',
    sa.Column('maGV', sa.CHAR(length=10), nullable=False),
    sa.Column('hoTen', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.CHAR(length=50), nullable=True),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('soDT', sa.CHAR(length=10), nullable=True),
    sa.Column('diaChi', sa.VARCHAR(length=50), nullable=True),
    sa.Column('maKhoa', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maKhoa'], ['khoa.maKhoa'], ),
    sa.PrimaryKeyConstraint('maGV')
    )
    op.create_table('monHoc',
    sa.Column('maMH', sa.CHAR(length=10), nullable=False),
    sa.Column('tenMonHoc', sa.VARCHAR(length=50), nullable=False),
    sa.Column('soTC', sa.Integer(), nullable=False),
    sa.Column('heSoTC', sa.Integer(), nullable=False),
    sa.Column('moTa', sa.Text(), nullable=True),
    sa.Column('trongSo_tx1', sa.Float(), nullable=False),
    sa.Column('trongSo_tx2', sa.Float(), nullable=False),
    sa.Column('trongSo_giuaKy', sa.Float(), nullable=False),
    sa.Column('trongSo_BaiThi', sa.Float(), nullable=False),
    sa.Column('giaTC', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('gia', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('ngayPhatHanh', sa.Date(), nullable=False),
    sa.Column('maKhoa', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maKhoa'], ['khoa.maKhoa'], ),
    sa.PrimaryKeyConstraint('maMH')
    )
    op.create_table('ct_ctdt',
    sa.Column('maCT', sa.CHAR(length=10), nullable=False),
    sa.Column('maNhom', sa.CHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['maCT'], ['ctdt.maCT'], ),
    sa.ForeignKeyConstraint(['maNhom'], ['nhomMH.maNhom'], ),
    sa.PrimaryKeyConstraint('maCT', 'maNhom')
    )
    op.create_table('ct_nmh',
    sa.Column('maNhom', sa.CHAR(length=20), nullable=False),
    sa.Column('maMH', sa.CHAR(length=10), nullable=False),
    sa.Column('ky', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maMH'], ['monHoc.maMH'], ),
    sa.ForeignKeyConstraint(['maNhom'], ['nhomMH.maNhom'], ),
    sa.PrimaryKeyConstraint('maNhom', 'maMH')
    )
    op.create_table('lopHoc',
    sa.Column('maLH', sa.CHAR(length=10), nullable=False),
    sa.Column('ngayBD', sa.Date(), nullable=True),
    sa.Column('ngayKT', sa.Date(), nullable=True),
    sa.Column('soPhong', sa.Integer(), nullable=True),
    sa.Column('hanHuy', sa.Date(), nullable=True),
    sa.Column('soTuanHoc', sa.Integer(), nullable=True),
    sa.Column('SisoThucTe', sa.Integer(), nullable=True),
    sa.Column('SisoToiDa', sa.Integer(), nullable=True),
    sa.Column('maMH', sa.CHAR(length=10), nullable=True),
    sa.Column('maGV', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maGV'], ['giangVien.maGV'], ),
    sa.ForeignKeyConstraint(['maMH'], ['monHoc.maMH'], ),
    sa.PrimaryKeyConstraint('maLH')
    )
    op.create_table('phuTrach',
    sa.Column('maMH', sa.CHAR(length=10), nullable=False),
    sa.Column('maGV', sa.CHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['maGV'], ['giangVien.maGV'], ),
    sa.ForeignKeyConstraint(['maMH'], ['monHoc.maMH'], ),
    sa.PrimaryKeyConstraint('maMH', 'maGV')
    )
    op.create_table('sinhVien',
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.Column('hoTen', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.CHAR(length=50), nullable=True),
    sa.Column('NgaySinh', sa.Date(), nullable=True),
    sa.Column('soDT', sa.CHAR(length=10), nullable=True),
    sa.Column('diaChi', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ngayTao', sa.DateTime(), nullable=True),
    sa.Column('ngayCapNhat', sa.DateTime(), nullable=True),
    sa.Column('maCT', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maCT'], ['ctdt.maCT'], ),
    sa.PrimaryKeyConstraint('maSV'),
    sa.UniqueConstraint('maSV')
    )
    op.create_table('tienQuyetMonHoc',
    sa.Column('maMH', sa.CHAR(length=10), nullable=False),
    sa.Column('maTQ', sa.CHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['maMH'], ['monHoc.maMH'], ),
    sa.ForeignKeyConstraint(['maTQ'], ['monHoc.maMH'], ),
    sa.PrimaryKeyConstraint('maMH', 'maTQ')
    )
    op.create_table('dieuKienTotNghiep',
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.Column('tb_GPA', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('DKSoTC', sa.Boolean(), nullable=True),
    sa.Column('DKTheChat', sa.Boolean(), nullable=True),
    sa.Column('DKNgoaiNgu', sa.Boolean(), nullable=True),
    sa.Column('DK_GDQP', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maSV'),
    sa.UniqueConstraint('maSV')
    )
    op.create_table('doiTuong',
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.Column('ho_Ngheo', sa.Boolean(), nullable=True),
    sa.Column('ho_Can_Ngheo', sa.Boolean(), nullable=True),
    sa.Column('mo_Coi', sa.Boolean(), nullable=True),
    sa.Column('khuyet_Tan', sa.Boolean(), nullable=True),
    sa.Column('dan_Toc', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quoc_Tich', sa.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maSV'),
    sa.UniqueConstraint('maSV')
    )
    op.create_table('giaoDich',
    sa.Column('maGD', sa.CHAR(length=10), nullable=False),
    sa.Column('tenGD', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ThanhTien', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('Cong_Tru', sa.Boolean(), nullable=True),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.Column('maMH', sa.CHAR(length=10), nullable=True),
    sa.Column('maKT', sa.CHAR(length=10), nullable=True),
    sa.Column('maSV', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maKT'], ['khoangThuKhac.maKT'], ),
    sa.ForeignKeyConstraint(['maMH'], ['monHoc.maMH'], ),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maGD')
    )
    op.create_table('ketQuaMonHoc',
    sa.Column('maKQ', sa.CHAR(length=10), nullable=False),
    sa.Column('tx1', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('tx2', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('giuaKy', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('BaiThi', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('diemGPA', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('diemChu', sa.CHAR(length=2), nullable=True),
    sa.Column('hocLai', sa.Boolean(), nullable=True),
    sa.Column('maKQHY', sa.CHAR(length=10), nullable=True),
    sa.Column('maMH', sa.CHAR(length=10), nullable=True),
    sa.Column('maSV', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maKQHY'], ['ketQuaHocKy.maKQHY'], ),
    sa.ForeignKeyConstraint(['maMH'], ['monHoc.maMH'], ),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maKQ')
    )
    op.create_table('lichHoc',
    sa.Column('maDOW', sa.CHAR(length=10), nullable=False),
    sa.Column('tietHoc', sa.VARCHAR(length=20), nullable=True),
    sa.Column('thu', sa.Integer(), nullable=True),
    sa.Column('tuanHoc', sa.Integer(), nullable=True),
    sa.Column('maLH', sa.CHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['maLH'], ['lopHoc.maLH'], ),
    sa.PrimaryKeyConstraint('maDOW')
    )
    op.create_table('lichThiSV',
    sa.Column('soBD', sa.Integer(), nullable=False),
    sa.Column('maSV', sa.CHAR(length=10), nullable=True),
    sa.Column('maLT', sa.CHAR(length=10), nullable=True),
    sa.Column('viTri', sa.CHAR(length=5), nullable=True),
    sa.Column('dieuKienThi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maLT'], ['lichThi.maLT'], ),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('soBD')
    )
    op.create_table('sinhVienLopHoc',
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.Column('maLH', sa.CHAR(length=10), nullable=False),
    sa.Column('NgayDK', sa.Date(), nullable=True),
    sa.Column('TrangThai_DK', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maLH'], ['lopHoc.maLH'], ),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maSV', 'maLH')
    )
    op.create_table('taiChinh',
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.Column('soDu', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('no', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('duocGiam', sa.Float(), nullable=True),
    sa.Column('hocBong', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maSV'),
    sa.UniqueConstraint('maSV')
    )
    op.create_table('taiKhoan',
    sa.Column('tenTaiKhoan', sa.CHAR(length=50), nullable=False),
    sa.Column('matKhau', sa.VARCHAR(length=255), nullable=True),
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('tenTaiKhoan'),
    sa.UniqueConstraint('tenTaiKhoan')
    )
    op.create_table('thucTap',
    sa.Column('maDN', sa.CHAR(length=10), nullable=False),
    sa.Column('maGV', sa.CHAR(length=10), nullable=False),
    sa.Column('maSV', sa.CHAR(length=10), nullable=False),
    sa.Column('viTriTT', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['maDN'], ['doanhNghiep.maDN'], ),
    sa.ForeignKeyConstraint(['maGV'], ['giangVien.maGV'], ),
    sa.ForeignKeyConstraint(['maSV'], ['sinhVien.maSV'], ),
    sa.PrimaryKeyConstraint('maDN', 'maGV', 'maSV')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.CHAR(length=50), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['taiKhoan.tenTaiKhoan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_username'), 'chat_message', ['username'], unique=False)
    op.create_table('lsgd',
    sa.Column('maLGD', sa.CHAR(length=10), nullable=False),
    sa.Column('maGD', sa.CHAR(length=10), nullable=True),
    sa.Column('ThoiGian', sa.DateTime(), nullable=True),
    sa.Column('TrangThai', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maGD'], ['giaoDich.maGD'], ),
    sa.PrimaryKeyConstraint('maLGD')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lsgd')
    op.drop_index(op.f('ix_chat_message_username'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('thucTap')
    op.drop_table('taiKhoan')
    op.drop_table('taiChinh')
    op.drop_table('sinhVienLopHoc')
    op.drop_table('lichThiSV')
    op.drop_table('lichHoc')
    op.drop_table('ketQuaMonHoc')
    op.drop_table('giaoDich')
    op.drop_table('doiTuong')
    op.drop_table('dieuKienTotNghiep')
    op.drop_table('tienQuyetMonHoc')
    op.drop_table('sinhVien')
    op.drop_table('phuTrach')
    op.drop_table('lopHoc')
    op.drop_table('ct_nmh')
    op.drop_table('ct_ctdt')
    op.drop_table('monHoc')
    op.drop_table('giangVien')
    op.drop_table('ctdt')
    op.drop_table('nhomMH')
    op.drop_table('lichThi')
    op.drop_table('khoangThuKhac')
    op.drop_table('khoa')
    op.drop_table('ketQuaHocKy')
    op.drop_table('doanhNghiep')
    # ### end Alembic commands ###
